// SPDX-License-Identifier: LicenseRef-MAFPlayground-NPU-1.0-CH
// Copyright (c) 2025 Jose Luis Latorre

using Microsoft.Agents.AI.Workflows;
using MAFPlayground.Samples.Sample22_WorkshopPlanner.Helpers;
using System.Text;

namespace MAFPlayground.Samples.Sample22_WorkshopPlanner.Executors;

/// <summary>
/// Executor that converts a workshop plan into a formatted markdown document.
/// </summary>
public static class MarkdownGenerationExecutor
{
    public static ValueTask<MarkdownDeliverable> ExecuteAsync(
        WorkshopPlan plan,
        IWorkflowContext ctx,
        CancellationToken ct)
    {
        Console.WriteLine("\n📝 [Markdown] Generating workshop document...");
        
        var markdown = GenerateWorkshopMarkdown(plan);
        var filename = SanitizeFilename(plan.WorkshopTitle) + ".md";
        
        var deliverable = new MarkdownDeliverable(filename, markdown);
        
        Console.WriteLine($"   Generated: {filename} ({markdown.Length:N0} characters)");
        
        return ValueTask.FromResult(deliverable);
    }

    private static string SanitizeFilename(string title)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var sanitized = string.Join("_", title.Split(invalid, StringSplitOptions.RemoveEmptyEntries)).TrimEnd('.');
        return sanitized.Replace(" ", "-").ToLowerInvariant();
    }

    private static string GenerateWorkshopMarkdown(WorkshopPlan plan)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine($"# {plan.WorkshopTitle}");
        sb.AppendLine();

        // Metadata
        sb.AppendLine("## Workshop Details");
        sb.AppendLine();
        sb.AppendLine($"**Duration:** {plan.TotalDurationHours} hours");
        sb.AppendLine();
        sb.AppendLine($"**Target Audience:** {plan.TargetAudience}");
        sb.AppendLine();

        // Overview
        sb.AppendLine("## Overview");
        sb.AppendLine();
        sb.AppendLine(plan.Overview);
        sb.AppendLine();

        // Modules
        sb.AppendLine("## Workshop Modules");
        sb.AppendLine();

        foreach (var module in plan.Modules)
        {
            sb.AppendLine($"### Module {module.ModuleNumber}: {module.Title}");
            sb.AppendLine();
            sb.AppendLine($"**Duration:** {module.DurationMinutes} minutes");
            sb.AppendLine();

            // Objectives
            sb.AppendLine("**Learning Objectives:**");
            foreach (var objective in module.Objectives)
            {
                sb.AppendLine($"- {objective}");
            }
            sb.AppendLine();

            // Content Sources
            if (module.ContentSources.Count > 0)
            {
                sb.AppendLine("**Content Sources:**");
                foreach (var source in module.ContentSources)
                {
                    sb.AppendLine($"- [{source.Title}]({source.Url})");
                    sb.AppendLine($"  - *{source.Usage}*");
                }
                sb.AppendLine();
            }

            // Activities
            if (module.Activities.Count > 0)
            {
                sb.AppendLine("**Activities:**");
                foreach (var activity in module.Activities)
                {
                    sb.AppendLine($"- {activity}");
                }
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine();
        }

        // Success Criteria
        sb.AppendLine("## Success Criteria");
        sb.AppendLine();
        sb.AppendLine("Participants will be successful if they can:");
        foreach (var criterion in plan.SuccessCriteria)
        {
            sb.AppendLine($"- {criterion}");
        }
        sb.AppendLine();

        // Additional Resources
        if (plan.Resources.Count > 0)
        {
            sb.AppendLine("## Additional Resources");
            sb.AppendLine();
            foreach (var resource in plan.Resources)
            {
                sb.AppendLine($"- {resource}");
            }
            sb.AppendLine();
        }

        // Footer
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine($"*Generated by AI Workshop Planner on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC*");

        return sb.ToString();
    }
}
